name: Testing workflow variables

on: 
  workflow_dispatch:

env:
  cloud: google.cloud  # Fixed typo from "google.clould"

jobs:
  greeting_job:
    runs-on: ubuntu-latest  # Corrected 'ubuntu.latest'
    env:
      Greeting: Hello
    steps:
      - name: Say Hello
        run: echo "$Greeting $First_name using $cloud"
        env:
          First_name: srija
